export const CHANGE_QUERY = 'CHANGE_QUERY'
export const REQUEST_ROBOTS = 'REQUEST_ROBOTS';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';